site_name: S-Parameter Viewer
docs_dir: doc
site_dir: htmldoc
use_directory_urls: false
nav:
  - index.md
  - howtorun.md
  - expressions.md
  - expr_networks.md
  - expr_sparams.md
  - expr_components.md
  - timedomain.md
  - tools.md
markdown_extensions:
  - tables
  - fenced_code
  - toc:
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
plugins: []  # disable search (won't work on local files anyway)
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
